dist: xenial
language: php
php:
 - 7.3

before_script:
  - LEVELDB_VERSION=f1463cb0b2486b0caf7d42ca3c7684545e875f04
  - curl -fsSL "https://github.com/pmmp/leveldb-mcpe/archive/f1463cb0b2486b0caf7d42ca3c7684545e875f04.tar.gz" | tar -zx
  - mv leveldb-mcpe-$LEVELDB_VERSION leveldb-mcpe
  - cd leveldb-mcpe && make -j4 && mv out-shared/libleveldb.* . && cd ..
  - git clone https://github.com/reeze/php-leveldb.git leveldb
  - cd leveldb && git checkout 9bcae79f71b81a5c3ea6f67e45ae9ae9fb2775a5
  - phpize
  - ./configure --with-leveldb=../leveldb-mcpe && make && make install
  - cd ..
  - git clone https://github.com/pmmp/ext-chunkutils2.git chunkutils
  - cd chunkutils && git checkout d8d762a597ac0da6f333f862096d6af0e6286b75
  - phpize
  - ./configure && make && make install
  - cd ..
  # - pecl install channel://pecl.php.net/pthreads-3.1.6
  - echo | pecl install channel://pecl.php.net/yaml-2.0.4
  - pecl install channel://pecl.php.net/crypto-0.3.1
  - pecl install channel://pecl.php.net/ds-1.2.9
  - pecl install channel://pecl.php.net/igbinary-3.0.1
  - git clone https://github.com/pmmp/pthreads.git
  - cd pthreads
  - git checkout 1b7da492b944146fa9680f6399bd9c6c6c6095e0
  - phpize
  - ./configure
  - make
  - make install
  - cd ..
  - echo "extension=pthreads.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - echo "extension=chunkutils2.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - echo "extension=leveldb.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - cd ${TRAVIS_BUILD_DIR}/.. && git clone --single-branch --branch master --recursive https://github.com/pmmp/PocketMine-MP.git
  - cd PocketMine-MP
  - composer install
  - php -dphar.readonly=0 ./build/server-phar.php ./PocketMine-MP.phar
  - mkdir plugins
  - cd ${TRAVIS_BUILD_DIR}/../PocketMine-MP/tests/plugins/PocketMine-DevTools
  - php -dphar.readonly=0 ./src/DevTools/ConsoleScript.php --make ./ --relative ./ --out ../../../plugins/DevTools.phar
  - cd ../../..
  - cp ${TRAVIS_BUILD_DIR}/tests/PluginChecker.phar plugins/PluginChecker.phar
  - mkdir unstaged && php ${TRAVIS_BUILD_DIR}/tests/travisPluginTest.php unstaged
  - cd ${TRAVIS_BUILD_DIR}
  - chmod 777 ${TRAVIS_BUILD_DIR}/tests/travisScript.sh
  - chmod 777 ${TRAVIS_BUILD_DIR}/tests/lint.sh
  - curl -sSLO https://github.com/phpstan/phpstan/releases/download/0.12.8/phpstan.phar
  - curl https://phar.phpunit.de/phpunit-7.phar --silent --location -o phpunit.phar

script:
 - ${TRAVIS_BUILD_DIR}/tests/lint.sh -p php -d ${TRAVIS_BUILD_DIR}/src/MyPlot
 - php phpstan.phar analyze --no-progress --memory-limit=2G || exit 1
# - (php phpunit.phar --bootstrap vendor/autoload.php --fail-on-warning tests/phpunit || exit 1) | bash -s -
 - cd ${TRAVIS_BUILD_DIR}/../PocketMine && ls
 - ${TRAVIS_BUILD_DIR}/tests/travisScript.sh MyPlot MyPlot
 - sed -i 's/world/Plots/' server.properties
 - ${TRAVIS_BUILD_DIR}/tests/travisScript.sh MyPlot MyPlot

deploy:
 provider: releases
 api_key: $GITHUB_TOKEN
 file_glob: true
 file: $TRAVIS_BUILD_DIR/../PocketMine/unstaged/MyPlot.phar
 skip_cleanup: true
 draft: true
 on:
  tags: true